print ("Hi my name is Rude_AI,")
Answer = input ("can I ask you some questions? ")
print ("Frick yea I can!!!")
Name = input ("What is your name? ")
print (Name, "? Thats the worst name I've ever heard, let me guess your ugly to")
Activity = input ("What do you do for fun? ")
print (Activity, "Wow you loser thats the most boring thing ever!!!")
Music = input ("What music do you like? ")
print  (Music, "Wow, You have a horrible name, your ugly, your boring, and you have no taste in music?... What kind of demon are you")
Sibs = input ("How many siblings do you have? ")
print (Sibs, "Wow that sucks! ")
Job = input ("What do you want to be when you grow up? ")
print (Job, "Wow I've already done that, I'm not sure what I want to be, but I'm sure that I don't want to be you!")


